title: DataRepublican
baseurl: ""
url: "https://datarepublican.com/"
destination: docs

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/default.png

include:
  - florida

favicon: /assets/images/favicon.png

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from