title: DataRepublican
baseurl: ""
url: "https://datarepublican.com/"
destination: docs

include:
  - florida

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from