// County name -> id of its path in _includes/map-florida.html.
const county_to_id = {
    "Alachua": "usfljs1",
    "Baker": "usfljs2",
    "Bay": "usfljs3",
    "Bradford": "usfljs4",
    "Brevard": "usfljs5",
    "Broward": "usfljs6",
    "Calhoun": "usfljs7",
    "Charlotte": "usfljs8",
    "Citrus": "usfljs9",
    "Clay": "usfljs10",
    "Collier": "usfljs11",
    "Columbia": "usfljs12",
    "DeSoto": "usfljs13",
    "Dixie": "usfljs14",
    "Duval": "usfljs15",
    "Escambia": "usfljs16",
    "Flagler": "usfljs17",
    "Franklin": "usfljs18",
    "Gadsden": "usfljs19",
    "Gilchrist": "usfljs20",
    "Glades": "usfljs21",
    "Gulf": "usfljs22",
    "Hamilton": "usfljs23",
    "Hardee": "usfljs24",
    "Hendry": "usfljs25",
    "Hernando": "usfljs26",
    "Highlands": "usfljs27",
    "Hillsborough": "usfljs28",
    "Holmes": "usfljs29",
    "Indian River": "usfljs30",
    "Jackson": "usfljs31",
    "Jefferson": "usfljs32",
    "Lafayette": "usfljs33",
    "Lake": "usfljs34",
    "Lee": "usfljs35",
    "Leon": "usfljs36",
    "Levy": "usfljs37",
    "Liberty": "usfljs38",
    "Madison": "usfljs39",
    "Manatee": "usfljs40",
    "Marion": "usfljs41",
    "Martin": "usfljs42",
    "Miami-Dade": "usfljs43",
    "Monroe": "usfljs44",
    "Nassau": "usfljs45",
    "Okaloosa": "usfljs46",
    "Okeechobee": "usfljs47",
    "Orange": "usfljs48",
    "Osceola": "usfljs49",
    "Palm Beach": "usfljs50",
    "Pasco": "usfljs51",
    "Pinellas": "usfljs52",
    "Polk": "usfljs53",
    "Putnam": "usfljs54",
    "Santa Rosa": "usfljs57",
    "Sarasota": "usfljs58",
    "Seminole": "usfljs59",
    "St. Johns": "usfljs55",
    "St. Lucie": "usfljs56",
    "Sumter": "usfljs60",
    "Suwannee": "usfljs61",
    "Taylor": "usfljs62",
    "Union": "usfljs63",
    "Volusia": "usfljs64",
    "Wakulla": "usfljs65",
    "Walton": "usfljs66",
    "Washington": "usfljs67"
};

var usfljsconfig = {"general": {
    "borderColor": "#9CA8B6",
    "visibleNames": "#adadad"
  }};

for (let county in county_to_id) {
    usfljsconfig[county_to_id[county]] = {
        "hover": county,
        "target": "none",
        "upColor": "#FFFFF3",
        "overColor": "#ECFFB3",
        "downColor": "#cae9af",
        "active": true
    };
}
